http:
  host: localhost
  port: 8000
  maxHeaderMegabytes: 1
  readTimeout: 10s
  writeTimeout: 10s

auth:
  tokenTTL: 180m

postgres:
  host: localhost
  port: 5432
  dbname: idler
  sslmode: disable

mongo: