http:
  port: 8000
  maxHeaderMegabytes: 1
  readTimeout: 10s
  writeTimeout: 10s

postgres:
  username: idler
  password: qwerty
  host: localhost
  port: 5432
  dbname: idler
  sslmode: disable

mongo: