http:
  host: localhost
  port: 8080
  maxHeaderMegabytes: 1
  readTimeout: 10s
  writeTimeout: 10s

auth:
  tokenTTL: 180m

postgres:
  host: localhost
  port: 5432
  dbname: idler
  sslmode: disable

redis:
  host: localhost
  port: 6379
  db: 0
  expires: 360m

mongo: